#!/usr/bin/env bash
# Regenerate every launch asset from the current product, in one go.
#
#   apps/launch/render.sh                 footage + final 1080p launch MP4 + README hero + store shots + docs shots
#   apps/launch/render.sh --draft         same, but the launch MP4 is a fast draft (24 fps, low bitrate)
#   apps/launch/render.sh --skip-build    reuse the current extension build (apps/extension/.output/chrome-mv3-e2e)
#   apps/launch/render.sh --skip-capture  reuse the footage in docs/launch/media/footage
#   apps/launch/render.sh --only launch|hero|store|docs     (needs footage from an earlier run)
#   apps/launch/render.sh --new-audio     regenerate the soundtrack even if docs/launch/media/track.mp3 exists
#
# Every heavy step (browsers, builds, ffmpeg) goes through research/heavy.sh, one at a time.
# Outputs (all gitignored except docs/screenshots):
#   docs/launch/media/launch-30s.mp4  (launch-draft.mp4 with --draft), poster.png, hero-{light,dark}.mp4
#   docs/screenshots/hero-{light,dark}.webp, before-after-*, editor-*, panel-*, export-*, guide-*, agent-skill-*  (committed)
#   docs/launch/store/0*.png           five 1280x800 Chrome Web Store screenshots
# The soundtrack is generated by audio/make-track.mjs (original, deterministic). To use your own music,
# put it at docs/launch/media/track.mp3 (30 s) and do not pass --new-audio.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
HEAVY="$ROOT/../research/heavy.sh"
MEDIA="$ROOT/docs/launch/media"
HF="$HERE/node_modules/.bin/hyperframes"

DRAFT=0; SKIP_BUILD=0; SKIP_CAPTURE=0; NEW_AUDIO=0; ONLY=""
while [ $# -gt 0 ]; do
  case "$1" in
    --draft) DRAFT=1 ;;
    --skip-build) SKIP_BUILD=1 ;;
    --skip-capture) SKIP_CAPTURE=1 ;;
    --new-audio) NEW_AUDIO=1 ;;
    --only) ONLY="$2"; shift ;;
    -h|--help) sed -n 2,20p "$0"; exit 0 ;;
    *) echo "unknown option $1" >&2; exit 2 ;;
  esac
  shift
done
want() { [ -z "$ONLY" ] || [ "$ONLY" = "$1" ]; }
step() { printf '\n== %s\n' "$*"; }
# research/heavy.sh (machine-wide job limiter) is used when present; elsewhere the commands just run.
heavy() { if [ -x "$HEAVY" ]; then "$HEAVY" "$@"; else "$@"; fi; }

mkdir -p "$MEDIA" "$ROOT/docs/screenshots" "$ROOT/docs/launch/store"

if [ -z "$ONLY" ] && [ "$SKIP_BUILD" = 0 ]; then
  step "extension e2e build"
  (cd "$ROOT" && heavy pnpm --filter @showsteps/extension build:e2e)
fi
if [ -z "$ONLY" ] && [ "$SKIP_CAPTURE" = 0 ]; then
  step "footage (Playwright drives the extension on the Acme Books fixtures)"
  (cd "$HERE" && heavy node capture/capture.mjs --theme both)
fi
if want launch && { [ "$NEW_AUDIO" = 1 ] || [ ! -f "$MEDIA/track.mp3" ]; }; then
  step "soundtrack (original, generated)"
  (cd "$HERE" && node audio/make-track.mjs --out "$MEDIA/track.mp3")
fi

if want launch; then
  step "launch video"
  (cd "$HERE" && node compose.mjs launch)
  if [ "$DRAFT" = 1 ]; then
    OUT="$MEDIA/launch-draft.mp4"; Q="--quality draft --fps 24"
  else
    OUT="$MEDIA/launch-30s.mp4"; Q="--quality delivery --fps 30"
  fi
  (cd "$HERE/.work/launch" && heavy "$HF" render $Q --output "$OUT")
  # poster frame (stays out of git with the rest of docs/launch/media)
  heavy ffmpeg -y -hide_banner -loglevel error -threads 4 -ss 7.2 -i "$OUT" -frames:v 1 "$MEDIA/poster.png"
  ffprobe -v error -show_entries format=duration,size:stream=codec_name,width,height -of default=nw=1 "$OUT"
fi

if want hero; then
  (cd "$HERE" && node compose.mjs hero)
  for THEME in light dark; do
    step "README hero ($THEME)"
    (cd "$HERE/.work/hero-$THEME" && heavy "$HF" render --quality looks --fps 15 --output "$MEDIA/hero-$THEME.mp4")
    heavy "$HERE/hero/to-webp.sh" "$MEDIA/hero-$THEME.mp4" "$ROOT/docs/screenshots/hero-$THEME.webp" 88
  done
fi

if want store; then
  step "store screenshots (1280x800)"
  (cd "$HERE" && heavy node store/make-store-shots.mjs)
fi
if want docs; then
  step "README screenshots"
  (cd "$HERE" && heavy node docs-shots/make-docs-shots.mjs)
fi
step "done"
ls -la "$MEDIA"/*.mp4 "$ROOT"/docs/screenshots/*.webp "$ROOT"/docs/launch/store/*.png 2>/dev/null | awk '{print $5"\t"$9}'
