// Generated by Showsteps (https://showsteps.vercel.app) from the guide "Invite a teammate", 6 steps.
// Run it with: npx playwright test replay.spec.ts
import { expect, test } from "@playwright/test";

test("Invite a teammate", async ({ context }) => {
  const page = await context.newPage();

  await test.step("1. Go to Settings – Acme", async () => {
    await page.goto("https://app.acme.test/settings");
    await expect(page).toHaveURL(/^https:\/\/app\.acme\.test\/settings\/?(?:[?#].*)?$/);
  });

  await test.step("2. Click Team", async () => {
    await page.getByRole("link", { name: "Team" }).click();
  });

  await test.step("3. Click Invite member", async () => {
    await page.getByRole("button", { name: "Invite member" }).click();
  });

  await test.step('4. Type "jane@example.com" in Email', async () => {
    await page.getByLabel("Email").fill("jane@example.com");
  });

  await test.step("5. Select Editor in Role", async () => {
    await page.getByLabel("Role").selectOption({ label: "Editor" });
  });

  await test.step("6. Click Send invite", async () => {
    await page.getByRole("button", { name: "Send invite" }).click();
  });
});
