import type { Guide } from "../schema";
import { PRODUCT_NAME, SITE_URL } from "../brand";
import { plainTitle } from "../text";
import { buildReplayPlan, q, stepLabel } from "./replay-plan";

export interface PlaywrightOptions {
  /** Add the recorded viewport as `test.use({ viewport })`. Default true. */
  viewport?: boolean;
}

/**
 * `replay.spec.ts`: an idiomatic `@playwright/test` file for the recording. Locators prefer
 * `getByTestId`, `getByRole`, `getByLabel`, `getByPlaceholder`, `getByText` and fall back to CSS/XPath;
 * iframes become `frameLocator` chains; only the first step of a tab uses `page.goto`, later
 * navigations become URL assertions. Values typed into sensitive fields are never written out: the
 * script reads them from `SHOWSTEPS_SECRET_<n>` environment variables.
 */
export function exportPlaywright(guide: Guide, opts: PlaywrightOptions = {}): string {
  const plan = buildReplayPlan(guide);
  const multi = plan.tabCount > 1;
  const out: string[] = [];
  const title = plainTitle(guide.title).replace(/\s+/g, " ").trim() || "Recorded guide";

  out.push(`// Generated by ${PRODUCT_NAME} (${SITE_URL}) from the guide ${q(title)}, ${plan.steps.length} step${plan.steps.length === 1 ? "" : "s"}.`);
  out.push("// Run it with: npx playwright test replay.spec.ts");
  if (plan.secrets.length) {
    out.push(`// Values typed into sensitive fields were never stored. Set ${plan.secrets.join(", ")} before running.`);
  }
  out.push(multi ? 'import { expect, test, type Page } from "@playwright/test";' : 'import { expect, test } from "@playwright/test";');
  out.push("");

  if (plan.secrets.length) {
    out.push("function secret(name: string): string {");
    out.push("  const value = process.env[name];");
    out.push("  if (value === undefined) throw new Error(`Set ${name} to replay this step: the recording did not store it.`);");
    out.push("  return value;");
    out.push("}");
    out.push("");
  }

  if (plan.viewport && opts.viewport !== false) {
    out.push(`test.use({ viewport: { width: ${plan.viewport.width}, height: ${plan.viewport.height} } });`);
    out.push("");
  }

  out.push(`test(${q(title)}, async ({ ${multi ? "page, context" : "page"} }) => {`);
  for (let i = 2; i <= plan.tabCount; i++) out.push(`  let page${i}!: Page;`);
  if (multi) out.push("");
  for (const line of plan.preamble) out.push(`  ${line}`);
  if (plan.preamble.length) out.push("");

  for (const ps of plan.steps) {
    const label = stepLabel(ps.step, ps.n);
    if (ps.step.action.type === "note") {
      out.push(`  // ${label} (note, not replayed)`);
      out.push("");
      continue;
    }
    if (!ps.replayable) {
      out.push(`  // ${label}: not replayed (${ps.note ?? "no replayable action"}).`);
      out.push("");
      continue;
    }
    out.push(`  await test.step(${q(label)}, async () => {`);
    for (const l of ps.lines) out.push(`    ${l}`);
    out.push("  });");
    out.push("");
  }
  while (out[out.length - 1] === "") out.pop();
  out.push("});");
  return out.join("\n") + "\n";
}
